# Generated by Django 4.2.11 on 2024-05-21 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_blobmodel_alter_fileupload_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSVFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv', models.JSONField()),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
