# Generated by Django 4.2.11 on 2024-05-30 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_csvfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_day',
            field=models.DateField(default='2023-05-30'),
            preserve_default=False,
        ),
    ]
