# Generated by Django 4.2.11 on 2024-05-31 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0008_alter_user_birth_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('DOB', models.DateField(null=True)),
                ('DEPT', models.CharField(max_length=20)),
            ],
        ),
    ]
