# Generated by Django 4.2.11 on 2024-05-31 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0009_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
